// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smn_base.proto

package pb;

public final class smn_base {
  private smn_base() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CallOrBuilder extends
      // @@protoc_insertion_point(interface_extends:smn_base.Call)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 dict = 1;</code>
     * @return The dict.
     */
    int getDict();

    /**
     * <code>bytes msg = 2;</code>
     * @return The msg.
     */
    com.google.protobuf.ByteString getMsg();
  }
  /**
   * Protobuf type {@code smn_base.Call}
   */
  public  static final class Call extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:smn_base.Call)
      CallOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Call.newBuilder() to construct.
    private Call(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Call() {
      msg_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Call();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Call(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              dict_ = input.readInt32();
              break;
            }
            case 18: {

              msg_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.smn_base.internal_static_smn_base_Call_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.smn_base.internal_static_smn_base_Call_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.smn_base.Call.class, pb.smn_base.Call.Builder.class);
    }

    public static final int DICT_FIELD_NUMBER = 1;
    private int dict_;
    /**
     * <code>int32 dict = 1;</code>
     * @return The dict.
     */
    public int getDict() {
      return dict_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString msg_;
    /**
     * <code>bytes msg = 2;</code>
     * @return The msg.
     */
    public com.google.protobuf.ByteString getMsg() {
      return msg_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dict_ != 0) {
        output.writeInt32(1, dict_);
      }
      if (!msg_.isEmpty()) {
        output.writeBytes(2, msg_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dict_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, dict_);
      }
      if (!msg_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, msg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pb.smn_base.Call)) {
        return super.equals(obj);
      }
      pb.smn_base.Call other = (pb.smn_base.Call) obj;

      if (getDict()
          != other.getDict()) return false;
      if (!getMsg()
          .equals(other.getMsg())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DICT_FIELD_NUMBER;
      hash = (53 * hash) + getDict();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pb.smn_base.Call parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.smn_base.Call parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.smn_base.Call parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.smn_base.Call parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.smn_base.Call parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.smn_base.Call parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.smn_base.Call parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.smn_base.Call parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.smn_base.Call parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pb.smn_base.Call parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.smn_base.Call parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.smn_base.Call parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pb.smn_base.Call prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code smn_base.Call}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:smn_base.Call)
        pb.smn_base.CallOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.smn_base.internal_static_smn_base_Call_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.smn_base.internal_static_smn_base_Call_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.smn_base.Call.class, pb.smn_base.Call.Builder.class);
      }

      // Construct using pb.smn_base.Call.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dict_ = 0;

        msg_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.smn_base.internal_static_smn_base_Call_descriptor;
      }

      @java.lang.Override
      public pb.smn_base.Call getDefaultInstanceForType() {
        return pb.smn_base.Call.getDefaultInstance();
      }

      @java.lang.Override
      public pb.smn_base.Call build() {
        pb.smn_base.Call result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pb.smn_base.Call buildPartial() {
        pb.smn_base.Call result = new pb.smn_base.Call(this);
        result.dict_ = dict_;
        result.msg_ = msg_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.smn_base.Call) {
          return mergeFrom((pb.smn_base.Call)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.smn_base.Call other) {
        if (other == pb.smn_base.Call.getDefaultInstance()) return this;
        if (other.getDict() != 0) {
          setDict(other.getDict());
        }
        if (other.getMsg() != com.google.protobuf.ByteString.EMPTY) {
          setMsg(other.getMsg());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.smn_base.Call parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.smn_base.Call) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int dict_ ;
      /**
       * <code>int32 dict = 1;</code>
       * @return The dict.
       */
      public int getDict() {
        return dict_;
      }
      /**
       * <code>int32 dict = 1;</code>
       * @param value The dict to set.
       * @return This builder for chaining.
       */
      public Builder setDict(int value) {
        
        dict_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dict = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDict() {
        
        dict_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString msg_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes msg = 2;</code>
       * @return The msg.
       */
      public com.google.protobuf.ByteString getMsg() {
        return msg_;
      }
      /**
       * <code>bytes msg = 2;</code>
       * @param value The msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes msg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:smn_base.Call)
    }

    // @@protoc_insertion_point(class_scope:smn_base.Call)
    private static final pb.smn_base.Call DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pb.smn_base.Call();
    }

    public static pb.smn_base.Call getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Call>
        PARSER = new com.google.protobuf.AbstractParser<Call>() {
      @java.lang.Override
      public Call parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Call(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Call> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Call> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pb.smn_base.Call getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:smn_base.Ret)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 dict = 1;</code>
     * @return The dict.
     */
    int getDict();

    /**
     * <code>bool Err = 2;</code>
     * @return The err.
     */
    boolean getErr();

    /**
     * <code>bytes msg = 3;</code>
     * @return The msg.
     */
    com.google.protobuf.ByteString getMsg();
  }
  /**
   * Protobuf type {@code smn_base.Ret}
   */
  public  static final class Ret extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:smn_base.Ret)
      RetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Ret.newBuilder() to construct.
    private Ret(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Ret() {
      msg_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Ret();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Ret(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              dict_ = input.readInt32();
              break;
            }
            case 16: {

              err_ = input.readBool();
              break;
            }
            case 26: {

              msg_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.smn_base.internal_static_smn_base_Ret_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.smn_base.internal_static_smn_base_Ret_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.smn_base.Ret.class, pb.smn_base.Ret.Builder.class);
    }

    public static final int DICT_FIELD_NUMBER = 1;
    private int dict_;
    /**
     * <code>int32 dict = 1;</code>
     * @return The dict.
     */
    public int getDict() {
      return dict_;
    }

    public static final int ERR_FIELD_NUMBER = 2;
    private boolean err_;
    /**
     * <code>bool Err = 2;</code>
     * @return The err.
     */
    public boolean getErr() {
      return err_;
    }

    public static final int MSG_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString msg_;
    /**
     * <code>bytes msg = 3;</code>
     * @return The msg.
     */
    public com.google.protobuf.ByteString getMsg() {
      return msg_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dict_ != 0) {
        output.writeInt32(1, dict_);
      }
      if (err_ != false) {
        output.writeBool(2, err_);
      }
      if (!msg_.isEmpty()) {
        output.writeBytes(3, msg_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dict_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, dict_);
      }
      if (err_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, err_);
      }
      if (!msg_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, msg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pb.smn_base.Ret)) {
        return super.equals(obj);
      }
      pb.smn_base.Ret other = (pb.smn_base.Ret) obj;

      if (getDict()
          != other.getDict()) return false;
      if (getErr()
          != other.getErr()) return false;
      if (!getMsg()
          .equals(other.getMsg())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DICT_FIELD_NUMBER;
      hash = (53 * hash) + getDict();
      hash = (37 * hash) + ERR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getErr());
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pb.smn_base.Ret parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.smn_base.Ret parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.smn_base.Ret parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.smn_base.Ret parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.smn_base.Ret parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.smn_base.Ret parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.smn_base.Ret parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.smn_base.Ret parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.smn_base.Ret parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pb.smn_base.Ret parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.smn_base.Ret parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.smn_base.Ret parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pb.smn_base.Ret prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code smn_base.Ret}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:smn_base.Ret)
        pb.smn_base.RetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.smn_base.internal_static_smn_base_Ret_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.smn_base.internal_static_smn_base_Ret_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.smn_base.Ret.class, pb.smn_base.Ret.Builder.class);
      }

      // Construct using pb.smn_base.Ret.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dict_ = 0;

        err_ = false;

        msg_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.smn_base.internal_static_smn_base_Ret_descriptor;
      }

      @java.lang.Override
      public pb.smn_base.Ret getDefaultInstanceForType() {
        return pb.smn_base.Ret.getDefaultInstance();
      }

      @java.lang.Override
      public pb.smn_base.Ret build() {
        pb.smn_base.Ret result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pb.smn_base.Ret buildPartial() {
        pb.smn_base.Ret result = new pb.smn_base.Ret(this);
        result.dict_ = dict_;
        result.err_ = err_;
        result.msg_ = msg_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.smn_base.Ret) {
          return mergeFrom((pb.smn_base.Ret)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.smn_base.Ret other) {
        if (other == pb.smn_base.Ret.getDefaultInstance()) return this;
        if (other.getDict() != 0) {
          setDict(other.getDict());
        }
        if (other.getErr() != false) {
          setErr(other.getErr());
        }
        if (other.getMsg() != com.google.protobuf.ByteString.EMPTY) {
          setMsg(other.getMsg());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.smn_base.Ret parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.smn_base.Ret) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int dict_ ;
      /**
       * <code>int32 dict = 1;</code>
       * @return The dict.
       */
      public int getDict() {
        return dict_;
      }
      /**
       * <code>int32 dict = 1;</code>
       * @param value The dict to set.
       * @return This builder for chaining.
       */
      public Builder setDict(int value) {
        
        dict_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dict = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDict() {
        
        dict_ = 0;
        onChanged();
        return this;
      }

      private boolean err_ ;
      /**
       * <code>bool Err = 2;</code>
       * @return The err.
       */
      public boolean getErr() {
        return err_;
      }
      /**
       * <code>bool Err = 2;</code>
       * @param value The err to set.
       * @return This builder for chaining.
       */
      public Builder setErr(boolean value) {
        
        err_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool Err = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearErr() {
        
        err_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString msg_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes msg = 3;</code>
       * @return The msg.
       */
      public com.google.protobuf.ByteString getMsg() {
        return msg_;
      }
      /**
       * <code>bytes msg = 3;</code>
       * @param value The msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes msg = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:smn_base.Ret)
    }

    // @@protoc_insertion_point(class_scope:smn_base.Ret)
    private static final pb.smn_base.Ret DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pb.smn_base.Ret();
    }

    public static pb.smn_base.Ret getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Ret>
        PARSER = new com.google.protobuf.AbstractParser<Ret>() {
      @java.lang.Override
      public Ret parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Ret(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Ret> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Ret> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pb.smn_base.Ret getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FPkgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:smn_base.FPkg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 NO = 1;</code>
     * @return The nO.
     */
    long getNO();

    /**
     * <code>bytes msg = 2;</code>
     * @return The msg.
     */
    com.google.protobuf.ByteString getMsg();

    /**
     * <code>bool Err = 3;</code>
     * @return The err.
     */
    boolean getErr();
  }
  /**
   * Protobuf type {@code smn_base.FPkg}
   */
  public  static final class FPkg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:smn_base.FPkg)
      FPkgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FPkg.newBuilder() to construct.
    private FPkg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FPkg() {
      msg_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FPkg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FPkg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              nO_ = input.readInt64();
              break;
            }
            case 18: {

              msg_ = input.readBytes();
              break;
            }
            case 24: {

              err_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.smn_base.internal_static_smn_base_FPkg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.smn_base.internal_static_smn_base_FPkg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.smn_base.FPkg.class, pb.smn_base.FPkg.Builder.class);
    }

    public static final int NO_FIELD_NUMBER = 1;
    private long nO_;
    /**
     * <code>int64 NO = 1;</code>
     * @return The nO.
     */
    public long getNO() {
      return nO_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString msg_;
    /**
     * <code>bytes msg = 2;</code>
     * @return The msg.
     */
    public com.google.protobuf.ByteString getMsg() {
      return msg_;
    }

    public static final int ERR_FIELD_NUMBER = 3;
    private boolean err_;
    /**
     * <code>bool Err = 3;</code>
     * @return The err.
     */
    public boolean getErr() {
      return err_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (nO_ != 0L) {
        output.writeInt64(1, nO_);
      }
      if (!msg_.isEmpty()) {
        output.writeBytes(2, msg_);
      }
      if (err_ != false) {
        output.writeBool(3, err_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (nO_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, nO_);
      }
      if (!msg_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, msg_);
      }
      if (err_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, err_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pb.smn_base.FPkg)) {
        return super.equals(obj);
      }
      pb.smn_base.FPkg other = (pb.smn_base.FPkg) obj;

      if (getNO()
          != other.getNO()) return false;
      if (!getMsg()
          .equals(other.getMsg())) return false;
      if (getErr()
          != other.getErr()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNO());
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (37 * hash) + ERR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getErr());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pb.smn_base.FPkg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.smn_base.FPkg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.smn_base.FPkg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.smn_base.FPkg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.smn_base.FPkg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.smn_base.FPkg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.smn_base.FPkg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.smn_base.FPkg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.smn_base.FPkg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pb.smn_base.FPkg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.smn_base.FPkg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.smn_base.FPkg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pb.smn_base.FPkg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code smn_base.FPkg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:smn_base.FPkg)
        pb.smn_base.FPkgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.smn_base.internal_static_smn_base_FPkg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.smn_base.internal_static_smn_base_FPkg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.smn_base.FPkg.class, pb.smn_base.FPkg.Builder.class);
      }

      // Construct using pb.smn_base.FPkg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nO_ = 0L;

        msg_ = com.google.protobuf.ByteString.EMPTY;

        err_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.smn_base.internal_static_smn_base_FPkg_descriptor;
      }

      @java.lang.Override
      public pb.smn_base.FPkg getDefaultInstanceForType() {
        return pb.smn_base.FPkg.getDefaultInstance();
      }

      @java.lang.Override
      public pb.smn_base.FPkg build() {
        pb.smn_base.FPkg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pb.smn_base.FPkg buildPartial() {
        pb.smn_base.FPkg result = new pb.smn_base.FPkg(this);
        result.nO_ = nO_;
        result.msg_ = msg_;
        result.err_ = err_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.smn_base.FPkg) {
          return mergeFrom((pb.smn_base.FPkg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.smn_base.FPkg other) {
        if (other == pb.smn_base.FPkg.getDefaultInstance()) return this;
        if (other.getNO() != 0L) {
          setNO(other.getNO());
        }
        if (other.getMsg() != com.google.protobuf.ByteString.EMPTY) {
          setMsg(other.getMsg());
        }
        if (other.getErr() != false) {
          setErr(other.getErr());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.smn_base.FPkg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.smn_base.FPkg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long nO_ ;
      /**
       * <code>int64 NO = 1;</code>
       * @return The nO.
       */
      public long getNO() {
        return nO_;
      }
      /**
       * <code>int64 NO = 1;</code>
       * @param value The nO to set.
       * @return This builder for chaining.
       */
      public Builder setNO(long value) {
        
        nO_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 NO = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNO() {
        
        nO_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString msg_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes msg = 2;</code>
       * @return The msg.
       */
      public com.google.protobuf.ByteString getMsg() {
        return msg_;
      }
      /**
       * <code>bytes msg = 2;</code>
       * @param value The msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes msg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }

      private boolean err_ ;
      /**
       * <code>bool Err = 3;</code>
       * @return The err.
       */
      public boolean getErr() {
        return err_;
      }
      /**
       * <code>bool Err = 3;</code>
       * @param value The err to set.
       * @return This builder for chaining.
       */
      public Builder setErr(boolean value) {
        
        err_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool Err = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearErr() {
        
        err_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:smn_base.FPkg)
    }

    // @@protoc_insertion_point(class_scope:smn_base.FPkg)
    private static final pb.smn_base.FPkg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pb.smn_base.FPkg();
    }

    public static pb.smn_base.FPkg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FPkg>
        PARSER = new com.google.protobuf.AbstractParser<FPkg>() {
      @java.lang.Override
      public FPkg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FPkg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FPkg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FPkg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pb.smn_base.FPkg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smn_base_Call_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smn_base_Call_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smn_base_Ret_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smn_base_Ret_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smn_base_FPkg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smn_base_FPkg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016smn_base.proto\022\010smn_base\"!\n\004Call\022\014\n\004di" +
      "ct\030\001 \001(\005\022\013\n\003msg\030\002 \001(\014\"-\n\003Ret\022\014\n\004dict\030\001 \001" +
      "(\005\022\013\n\003Err\030\002 \001(\010\022\013\n\003msg\030\003 \001(\014\",\n\004FPkg\022\n\n\002" +
      "NO\030\001 \001(\003\022\013\n\003msg\030\002 \001(\014\022\013\n\003Err\030\003 \001(\010B\016\n\002pb" +
      "B\010smn_baseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_smn_base_Call_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smn_base_Call_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smn_base_Call_descriptor,
        new java.lang.String[] { "Dict", "Msg", });
    internal_static_smn_base_Ret_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smn_base_Ret_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smn_base_Ret_descriptor,
        new java.lang.String[] { "Dict", "Err", "Msg", });
    internal_static_smn_base_FPkg_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smn_base_FPkg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smn_base_FPkg_descriptor,
        new java.lang.String[] { "NO", "Msg", "Err", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
