// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smn_dict.proto

package pb;

public final class smn_dict {
  private smn_dict() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code smn_dict.EDict}
   */
  public enum EDict
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>None = 0;</code>
     */
    None(0),
    /**
     * <code>rip_ano_rpc_itf_Login_Test1_Prm = 1;</code>
     */
    rip_ano_rpc_itf_Login_Test1_Prm(1),
    /**
     * <code>rip_ano_rpc_itf_Login_Test1_Ret = 2;</code>
     */
    rip_ano_rpc_itf_Login_Test1_Ret(2),
    /**
     * <code>rip_ano_rpc_itf_Login_Test2_Prm = 3;</code>
     */
    rip_ano_rpc_itf_Login_Test2_Prm(3),
    /**
     * <code>rip_ano_rpc_itf_Login_Test2_Ret = 4;</code>
     */
    rip_ano_rpc_itf_Login_Test2_Ret(4),
    /**
     * <code>rip_ano_rpc_itf_MutiTest_SendMsg_Prm = 5;</code>
     */
    rip_ano_rpc_itf_MutiTest_SendMsg_Prm(5),
    /**
     * <code>rip_ano_rpc_itf_MutiTest_SendMsg_Ret = 6;</code>
     */
    rip_ano_rpc_itf_MutiTest_SendMsg_Ret(6),
    /**
     * <code>rip_ano_rpc_itf_Login_DoLogin_Prm = 7;</code>
     */
    rip_ano_rpc_itf_Login_DoLogin_Prm(7),
    /**
     * <code>rip_ano_rpc_itf_Login_DoLogin_Ret = 8;</code>
     */
    rip_ano_rpc_itf_Login_DoLogin_Ret(8),
    /**
     * <code>rip_rpc_itf_Login_DoLogin_Prm = 9;</code>
     */
    rip_rpc_itf_Login_DoLogin_Prm(9),
    /**
     * <code>rip_rpc_itf_Login_DoLogin_Ret = 10;</code>
     */
    rip_rpc_itf_Login_DoLogin_Ret(10),
    /**
     * <code>rip_rpc_itf_Login_Test1_Prm = 11;</code>
     */
    rip_rpc_itf_Login_Test1_Prm(11),
    /**
     * <code>rip_rpc_itf_Login_Test1_Ret = 12;</code>
     */
    rip_rpc_itf_Login_Test1_Ret(12),
    /**
     * <code>rip_rpc_itf_Login_Test2_Prm = 13;</code>
     */
    rip_rpc_itf_Login_Test2_Prm(13),
    /**
     * <code>rip_rpc_itf_Login_Test2_Ret = 14;</code>
     */
    rip_rpc_itf_Login_Test2_Ret(14),
    /**
     * <code>rip_rpc_itf_MutiTest_SendMsg_Prm = 15;</code>
     */
    rip_rpc_itf_MutiTest_SendMsg_Prm(15),
    /**
     * <code>rip_rpc_itf_MutiTest_SendMsg_Ret = 16;</code>
     */
    rip_rpc_itf_MutiTest_SendMsg_Ret(16),
    /**
     * <code>smn_base_Call = 17;</code>
     */
    smn_base_Call(17),
    /**
     * <code>smn_base_Ret = 18;</code>
     */
    smn_base_Ret(18),
    /**
     * <code>smn_base_FPkg = 19;</code>
     */
    smn_base_FPkg(19),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>None = 0;</code>
     */
    public static final int None_VALUE = 0;
    /**
     * <code>rip_ano_rpc_itf_Login_Test1_Prm = 1;</code>
     */
    public static final int rip_ano_rpc_itf_Login_Test1_Prm_VALUE = 1;
    /**
     * <code>rip_ano_rpc_itf_Login_Test1_Ret = 2;</code>
     */
    public static final int rip_ano_rpc_itf_Login_Test1_Ret_VALUE = 2;
    /**
     * <code>rip_ano_rpc_itf_Login_Test2_Prm = 3;</code>
     */
    public static final int rip_ano_rpc_itf_Login_Test2_Prm_VALUE = 3;
    /**
     * <code>rip_ano_rpc_itf_Login_Test2_Ret = 4;</code>
     */
    public static final int rip_ano_rpc_itf_Login_Test2_Ret_VALUE = 4;
    /**
     * <code>rip_ano_rpc_itf_MutiTest_SendMsg_Prm = 5;</code>
     */
    public static final int rip_ano_rpc_itf_MutiTest_SendMsg_Prm_VALUE = 5;
    /**
     * <code>rip_ano_rpc_itf_MutiTest_SendMsg_Ret = 6;</code>
     */
    public static final int rip_ano_rpc_itf_MutiTest_SendMsg_Ret_VALUE = 6;
    /**
     * <code>rip_ano_rpc_itf_Login_DoLogin_Prm = 7;</code>
     */
    public static final int rip_ano_rpc_itf_Login_DoLogin_Prm_VALUE = 7;
    /**
     * <code>rip_ano_rpc_itf_Login_DoLogin_Ret = 8;</code>
     */
    public static final int rip_ano_rpc_itf_Login_DoLogin_Ret_VALUE = 8;
    /**
     * <code>rip_rpc_itf_Login_DoLogin_Prm = 9;</code>
     */
    public static final int rip_rpc_itf_Login_DoLogin_Prm_VALUE = 9;
    /**
     * <code>rip_rpc_itf_Login_DoLogin_Ret = 10;</code>
     */
    public static final int rip_rpc_itf_Login_DoLogin_Ret_VALUE = 10;
    /**
     * <code>rip_rpc_itf_Login_Test1_Prm = 11;</code>
     */
    public static final int rip_rpc_itf_Login_Test1_Prm_VALUE = 11;
    /**
     * <code>rip_rpc_itf_Login_Test1_Ret = 12;</code>
     */
    public static final int rip_rpc_itf_Login_Test1_Ret_VALUE = 12;
    /**
     * <code>rip_rpc_itf_Login_Test2_Prm = 13;</code>
     */
    public static final int rip_rpc_itf_Login_Test2_Prm_VALUE = 13;
    /**
     * <code>rip_rpc_itf_Login_Test2_Ret = 14;</code>
     */
    public static final int rip_rpc_itf_Login_Test2_Ret_VALUE = 14;
    /**
     * <code>rip_rpc_itf_MutiTest_SendMsg_Prm = 15;</code>
     */
    public static final int rip_rpc_itf_MutiTest_SendMsg_Prm_VALUE = 15;
    /**
     * <code>rip_rpc_itf_MutiTest_SendMsg_Ret = 16;</code>
     */
    public static final int rip_rpc_itf_MutiTest_SendMsg_Ret_VALUE = 16;
    /**
     * <code>smn_base_Call = 17;</code>
     */
    public static final int smn_base_Call_VALUE = 17;
    /**
     * <code>smn_base_Ret = 18;</code>
     */
    public static final int smn_base_Ret_VALUE = 18;
    /**
     * <code>smn_base_FPkg = 19;</code>
     */
    public static final int smn_base_FPkg_VALUE = 19;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EDict valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EDict forNumber(int value) {
      switch (value) {
        case 0: return None;
        case 1: return rip_ano_rpc_itf_Login_Test1_Prm;
        case 2: return rip_ano_rpc_itf_Login_Test1_Ret;
        case 3: return rip_ano_rpc_itf_Login_Test2_Prm;
        case 4: return rip_ano_rpc_itf_Login_Test2_Ret;
        case 5: return rip_ano_rpc_itf_MutiTest_SendMsg_Prm;
        case 6: return rip_ano_rpc_itf_MutiTest_SendMsg_Ret;
        case 7: return rip_ano_rpc_itf_Login_DoLogin_Prm;
        case 8: return rip_ano_rpc_itf_Login_DoLogin_Ret;
        case 9: return rip_rpc_itf_Login_DoLogin_Prm;
        case 10: return rip_rpc_itf_Login_DoLogin_Ret;
        case 11: return rip_rpc_itf_Login_Test1_Prm;
        case 12: return rip_rpc_itf_Login_Test1_Ret;
        case 13: return rip_rpc_itf_Login_Test2_Prm;
        case 14: return rip_rpc_itf_Login_Test2_Ret;
        case 15: return rip_rpc_itf_MutiTest_SendMsg_Prm;
        case 16: return rip_rpc_itf_MutiTest_SendMsg_Ret;
        case 17: return smn_base_Call;
        case 18: return smn_base_Ret;
        case 19: return smn_base_FPkg;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EDict>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EDict> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EDict>() {
            public EDict findValueByNumber(int number) {
              return EDict.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return pb.smn_dict.getDescriptor().getEnumTypes().get(0);
    }

    private static final EDict[] VALUES = values();

    public static EDict valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EDict(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:smn_dict.EDict)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016smn_dict.proto\022\010smn_dict*\225\005\n\005EDict\022\010\n\004" +
      "None\020\000\022#\n\037rip_ano_rpc_itf_Login_Test1_Pr" +
      "m\020\001\022#\n\037rip_ano_rpc_itf_Login_Test1_Ret\020\002" +
      "\022#\n\037rip_ano_rpc_itf_Login_Test2_Prm\020\003\022#\n" +
      "\037rip_ano_rpc_itf_Login_Test2_Ret\020\004\022(\n$ri" +
      "p_ano_rpc_itf_MutiTest_SendMsg_Prm\020\005\022(\n$" +
      "rip_ano_rpc_itf_MutiTest_SendMsg_Ret\020\006\022%" +
      "\n!rip_ano_rpc_itf_Login_DoLogin_Prm\020\007\022%\n" +
      "!rip_ano_rpc_itf_Login_DoLogin_Ret\020\010\022!\n\035" +
      "rip_rpc_itf_Login_DoLogin_Prm\020\t\022!\n\035rip_r" +
      "pc_itf_Login_DoLogin_Ret\020\n\022\037\n\033rip_rpc_it" +
      "f_Login_Test1_Prm\020\013\022\037\n\033rip_rpc_itf_Login" +
      "_Test1_Ret\020\014\022\037\n\033rip_rpc_itf_Login_Test2_" +
      "Prm\020\r\022\037\n\033rip_rpc_itf_Login_Test2_Ret\020\016\022$" +
      "\n rip_rpc_itf_MutiTest_SendMsg_Prm\020\017\022$\n " +
      "rip_rpc_itf_MutiTest_SendMsg_Ret\020\020\022\021\n\rsm" +
      "n_base_Call\020\021\022\020\n\014smn_base_Ret\020\022\022\021\n\rsmn_b" +
      "ase_FPkg\020\023B\016\n\002pbB\010smn_dictb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
